template:
  path: vpc.yaml.j2
  type: file
parameters:
  EnvironmentName: dev
  VpcCIDR: 10.11.0.0/16
  PublicSubnet1CIDR: 10.11.10.0/24
  PublicSubnet2CIDR: 10.11.11.0/24
  PrivateSubnet1CIDR: 10.11.20.0/24
  PrivateSubnet2CIDR: 10.11.21.0/24