template:
  path: alb.yaml.j2
  type: file
parameters:
  Subneta: !stack_output_external gospa-app-project-dev-vpc::PublicSubnet1
  Subneta: !stack_output_external gospa-app-project-dev-vpc::PublicSubnet1
  AlbName: "go-spa-alb"
  LBScheme: "internet"
  AlbSecurityGroup: !stack_output_external security-groups-dev-ec2-rds-alb-sg::RDSSG
  s3LogsEnabled: 'true'
  s3LoggingBucket: !stack_output_external storage-dev-s3-elb-logging-bucket::S3Bucket
  s3LoggingPrefix: "go-spa-alb-logging"
  ALBType: "application"
  IpAddressType: "ipv4"
  
