template:
  path: secrets-manager.yaml.j2
  type: file

sceptre_user_data:
  SecretEntries:
  -           
    GOSPARDSSecret:
      Description: "This is a Secrets Manager secret for Go SPA RDS DB instance"        
      GenerateSecretString:          
        ExcludeLowercase: False          
        ExcludeNumbers: False          
        ExcludePunctuation: True          
        ExcludeUppercase: False          
        GenerateStringKey: password          
        IncludeSpace: False          
        PasswordLength: 16          
        RequireEachIncludedType: True
        ExcludeCharacters: '\"@/\'
        SecretStringTemplate: '"{\"DbUser\": \"postgres\",\"DbPassword\": \"password\"}"'
      Name: GOSPARDSSecret