template:
  path: iam.yaml.j2
  type: file

sceptre_user_data:
  ServiceName: s3-access-role
  AssumeRolePolicyDocument:
    Version: "2012-10-17"
    Statement:
      - Effect: "Allow"
        Principal:
          Service:
            - "ec2.amazonaws.com"
            - "rds.amazonaws.com"
            - "elasticloadbalancing.amazonaws.com"
        Action: "sts:AssumeRole"

  PolicyDocument:
    Version: "2012-10-17"
    Statement:
      - Effect: Allow
        Action:
        - "s3:Get*"
        - "s3:List*"
        - "s3:Put*"
        - "s3:AbortMultipartUpload"
        - "kms:*"
        Resource: 
          - "arn:aws:s3:::go-spa-project-source-code"
          - "arn:aws:s3:::go-spa-project-source-code/*"
      - Effect: Allow
        Action: "s3:ListAllMyBuckets"
        Resource: 
          - "*"
