template:
  path: s3.yaml.j2
  type: file
parameters: {}
sceptre_user_data:
  bucket_name: go-spa-project-source-code
  server_side_encryption_algorithm: 'aws:kms'
  BlockPublicAcls: true 
  BlockPublicPolicy: true
  IgnorePublicAcls: true 
  RestrictPublicBuckets: true
  PolicyDocument:
    Version: "2012-10-17"
    Statement:
      - Effect: Allow
        Principal:
          AWS:
            - "arn:aws:iam::580243929783:user/DevOps"
        Action:
        - "s3:Get*"
        - "s3:List*"
        - "s3:Put*"
        - "s3:GetObject"
        - "s3:PutObjectAcl"
        Resource: 
          - "arn:aws:s3:::go-spa-project-source-code" # Change based on env
          - "arn:aws:s3:::go-spa-project-source-code/*" # Change based on env
      
  
