template:
  path: waf-ip-set.yaml.j2
  type: file

sceptre_user_data:
  IP_Sets:
  - IPAddressSet:
      IpSetDescription: My Home IP
      IpSetName: Home-IP
      IpSetScope: REGIONAL
      IpSetIPVersion: IPV4
      IpSetAddresses:
        - 10.199.120.58/32
        - 10.199.120.59/32