template:
  path: webrules.yaml.j2
  type: file

sceptre_user_data:
  Web_Acls:
  - WebAclRules:
      WebACLName: test
      WebAclDescription: WEB ACL Rules
      Scope: REGIONAL
      VisibilityConfig:
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: Allow-Home-Public-IP
      DefaultAction:
        Block: {}
      Rules:
        - Name: Allow-Home-Public-IP
          Priority: 0
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: Allow-Home-Public-IP
          Action:
            Allow: {}
          Statement:
            IPSetReferenceStatement:
              Arn: "arn:aws:wafv2:ap-southeast-2:580243979783:regional/ipset/Home-IP/aa6d4453-1d3d-482a-ac3b-e29a6914a086"