template:
  path: webrules-association.yaml.j2
  type: file

sceptre_user_data:
  Web_Acl_Associations:
  - WebACLAssociations: # This is the name of the resource
      WebACLArn: !stack_output_external waf-dev-webrules::WebAclRules'
      ResourceArn: !stack_output_external alb-dev-alb-internet-facing::AlbArn'